import React, { useState } from 'react';
import { useParams } from 'react-router-dom';

const ProductDetails = () => {
  const { id } = useParams();
  const [quantity, setQuantity] = useState(1);
  const [selectedSize, setSelectedSize] = useState('M');

  const products = [
    // New Arrivals (IDs 1-30)
    { id: 1, name: 'Silk Anarkali Kurti', price: 2499, image: 'https://via.placeholder.com/300?text=Silk+Anarkali+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'A luxurious silk anarkali kurti for festive occasions.', color: 'Royal Blue', material: '100% Silk' },
    { id: 2, name: 'Cotton Straight Kurti', price: 899, image: 'https://via.placeholder.com/300?text=Cotton+Straight+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Comfortable straight kurti for daily wear.', color: 'Off White', material: 'Pure Cotton' },
    { id: 3, name: 'Embroidered Georgette Kurti', price: 1799, image: 'https://via.placeholder.com/300?text=Embroidered+Georgette+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Elegant georgette kurti with embroidery.', color: 'Maroon', material: 'Georgette' },
    { id: 4, name: 'Printed Rayon Kurti', price: 1199, image: 'https://via.placeholder.com/300?text=Printed+Rayon+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Stylish rayon kurti with vibrant prints.', color: 'Multicolor', material: 'Rayon' },
    { id: 5, name: 'Chiffon Layered Kurti', price: 1599, image: 'https://via.placeholder.com/300?text=Chiffon+Layered+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Graceful layered kurti in chiffon.', color: 'Pink', material: 'Chiffon' },
    { id: 6, name: 'Velvet Kurti with Zari', price: 2999, image: 'https://via.placeholder.com/300?text=Velvet+Kurti+with+Zari', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Rich velvet kurti with zari work.', color: 'Green', material: 'Velvet' },
    { id: 7, name: 'Linen Straight Kurti', price: 1399, image: 'https://via.placeholder.com/300?text=Linen+Straight+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Breathable linen kurti for summer.', color: 'Beige', material: 'Linen' },
    { id: 8, name: 'Handwoven Silk Kurti', price: 3499, image: 'https://via.placeholder.com/300?text=Handwoven+Silk+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Exquisite handwoven silk kurti.', color: 'Gold', material: 'Silk' },
    { id: 9, name: 'Cotton Block Print Kurti', price: 999, image: 'https://via.placeholder.com/300?text=Cotton+Block+Print+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Traditional block print cotton kurti.', color: 'Red', material: 'Cotton' },
    { id: 10, name: 'Georgette A-Line Kurti', price: 1699, image: 'https://via.placeholder.com/300?text=Georgette+A-Line+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Flowy A-line kurti in georgette.', color: 'Yellow', material: 'Georgette' },
    { id: 11, name: 'Rayon Palazzo Kurti Set', price: 1899, image: 'https://via.placeholder.com/300?text=Rayon+Palazzo+Kurti+Set', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Elegant kurti with palazzo pants.', color: 'Navy Blue', material: 'Rayon' },
    { id: 12, name: 'Silk Embroidered Kurti', price: 2799, image: 'https://via.placeholder.com/300?text=Silk+Embroidered+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Silk kurti with intricate embroidery.', color: 'Purple', material: 'Silk' },
    { id: 13, name: 'Cotton Asymmetrical Kurti', price: 1299, image: 'https://via.placeholder.com/300?text=Cotton+Asymmetrical+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Modern asymmetrical cotton kurti.', color: 'Grey', material: 'Cotton' },
    { id: 14, name: 'Chanderi Kurti with Dupatta', price: 2299, image: 'https://via.placeholder.com/300?text=Chanderi+Kurti+with+Dupatta', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Chanderi kurti with matching dupatta.', color: 'Peach', material: 'Chanderi Silk' },
    { id: 15, name: 'Printed Cotton Kurti', price: 799, image: 'https://via.placeholder.com/300?text=Printed+Cotton+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Casual printed cotton kurti.', color: 'Green', material: 'Cotton' },
    { id: 16, name: 'Silk Straight Kurti', price: 1999, image: 'https://via.placeholder.com/300?text=Silk+Straight+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Classic straight silk kurti.', color: 'Black', material: 'Silk' },
    { id: 17, name: 'Georgette Flared Kurti', price: 1499, image: 'https://via.placeholder.com/300?text=Georgette+Flared+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Flared georgette kurti for elegance.', color: 'Pink', material: 'Georgette' },
    { id: 18, name: 'Rayon Anarkali Kurti', price: 2099, image: 'https://via.placeholder.com/300?text=Rayon+Anarkali+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Flowy rayon anarkali kurti.', color: 'Red', material: 'Rayon' },
    { id: 19, name: 'Cotton Kurti with Jacket', price: 1599, image: 'https://via.placeholder.com/300?text=Cotton+Kurti+with+Jacket', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Cotton kurti with stylish jacket.', color: 'Blue', material: 'Cotton' },
    { id: 20, name: 'Velvet Straight Kurti', price: 2699, image: 'https://via.placeholder.com/300?text=Velvet+Straight+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Luxurious straight velvet kurti.', color: 'Maroon', material: 'Velvet' },
    { id: 21, name: 'Linen Embroidered Kurti', price: 1799, image: 'https://via.placeholder.com/300?text=Linen+Embroidered+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Linen kurti with delicate embroidery.', color: 'White', material: 'Linen' },
    { id: 22, name: 'Silk Kurti with Palazzo', price: 3199, image: 'https://via.placeholder.com/300?text=Silk+Kurti+with+Palazzo', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Silk kurti with palazzo set.', color: 'Gold', material: 'Silk' },
    { id: 23, name: 'Cotton Kurti with Skirt', price: 1399, image: 'https://via.placeholder.com/300?text=Cotton+Kurti+with+Skirt', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Cotton kurti with matching skirt.', color: 'Yellow', material: 'Cotton' },
    { id: 24, name: 'Chiffon Straight Kurti', price: 1299, image: 'https://via.placeholder.com/300?text=Chiffon+Straight+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Lightweight chiffon straight kurti.', color: 'Green', material: 'Chiffon' },
    { id: 25, name: 'Printed Georgette Kurti', price: 1099, image: 'https://via.placeholder.com/300?text=Printed+Georgette+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Printed georgette kurti for casual wear.', color: 'Multicolor', material: 'Georgette' },
    { id: 26, name: 'Rayon Kurti with Dupatta', price: 1999, image: 'https://via.placeholder.com/300?text=Rayon+Kurti+with+Dupatta', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Rayon kurti with matching dupatta.', color: 'Pink', material: 'Rayon' },
    { id: 27, name: 'Silk Kurti with Embroidery', price: 2599, image: 'https://via.placeholder.com/300?text=Silk+Kurti+with+Embroidery', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Silk kurti with detailed embroidery.', color: 'Purple', material: 'Silk' },
    { id: 28, name: 'Cotton Flared Kurti', price: 1199, image: 'https://via.placeholder.com/300?text=Cotton+Flared+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Flared cotton kurti for comfort.', color: 'Blue', material: 'Cotton' },
    { id: 29, name: 'Velvet Anarkali Kurti', price: 3299, image: 'https://via.placeholder.com/300?text=Velvet+Anarkali+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Opulent velvet anarkali kurti.', color: 'Red', material: 'Velvet' },
    { id: 30, name: 'Linen Printed Kurti', price: 1499, image: 'https://via.placeholder.com/300?text=Linen+Printed+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Printed linen kurti for a chic look.', color: 'Beige', material: 'Linen' },
    
    // Indian Wear (IDs 31-60)
    { id: 31, name: 'Anarkali Silk Kurti', price: 2599, image: 'https://via.placeholder.com/300?text=Anarkali+Silk+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Traditional silk anarkali kurti.', color: 'Red', material: 'Silk' },
    { id: 32, name: 'Cotton Churidar Kurti', price: 999, image: 'https://via.placeholder.com/300?text=Cotton+Churidar+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Classic cotton kurti with churidar.', color: 'Yellow', material: 'Cotton' },
    { id: 33, name: 'Embroidered Lehenga Kurti', price: 2999, image: 'https://via.placeholder.com/300?text=Embroidered+Lehenga+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Festive lehenga-style kurti with embroidery.', color: 'Green', material: 'Georgette' },
    { id: 34, name: 'Printed Dhoti Kurti', price: 1299, image: 'https://via.placeholder.com/300?text=Printed+Dhoti+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Trendy dhoti-style kurti with prints.', color: 'Blue', material: 'Rayon' },
    { id: 35, name: 'Chiffon Saree Kurti', price: 1699, image: 'https://via.placeholder.com/300?text=Chiffon+Saree+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Saree-inspired chiffon kurti.', color: 'Pink', material: 'Chiffon' },
    { id: 36, name: 'Velvet Salwar Kurti', price: 2799, image: 'https://via.placeholder.com/300?text=Velvet+Salwar+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Velvet kurti with salwar.', color: 'Maroon', material: 'Velvet' },
    { id: 37, name: 'Linen Straight Kurti', price: 1399, image: 'https://via.placeholder.com/300?text=Linen+Straight+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Simple linen straight kurti.', color: 'White', material: 'Linen' },
    { id: 38, name: 'Handwoven Banarasi Kurti', price: 3999, image: 'https://via.placeholder.com/300?text=Handwoven+Banarasi+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Luxurious handwoven Banarasi kurti.', color: 'Gold', material: 'Banarasi Silk' },
    { id: 39, name: 'Cotton Phulkari Kurti', price: 1099, image: 'https://via.placeholder.com/300?text=Cotton+Phulkari+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Traditional Phulkari embroidered kurti.', color: 'Red', material: 'Cotton' },
    { id: 40, name: 'Georgette Sharara Kurti', price: 1899, image: 'https://via.placeholder.com/300?text=Georgette+Sharara+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Elegant sharara-style kurti.', color: 'Pink', material: 'Georgette' },
    { id: 41, name: 'Rayon Palazzo Set', price: 1999, image: 'https://via.placeholder.com/300?text=Rayon+Palazzo+Set', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Rayon kurti with palazzo pants.', color: 'Navy Blue', material: 'Rayon' },
    { id: 42, name: 'Silk Kurta with Dupatta', price: 2899, image: 'https://via.placeholder.com/300?text=Silk+Kurta+with+Dupatta', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Silk kurta with matching dupatta.', color: 'Purple', material: 'Silk' },
    { id: 43, name: 'Cotton Asymmetrical Kurti', price: 1199, image: 'https://via.placeholder.com/300?text=Cotton+Asymmetrical+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Unique asymmetrical cotton kurti.', color: 'Grey', material: 'Cotton' },
    { id: 44, name: 'Chanderi Anarkali Set', price: 2399, image: 'https://via.placeholder.com/300?text=Chanderi+Anarkali+Set', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Chanderi anarkali with dupatta.', color: 'Peach', material: 'Chanderi Silk' },
    { id: 45, name: 'Printed Kota Kurti', price: 899, image: 'https://via.placeholder.com/300?text=Printed+Kota+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Lightweight printed kota kurti.', color: 'Green', material: 'Kota Cotton' },
    { id: 46, name: 'Silk Straight Kurta', price: 2099, image: 'https://via.placeholder.com/300?text=Silk+Straight+Kurta', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Elegant straight silk kurta.', color: 'Black', material: 'Silk' },
    { id: 47, name: 'Georgette Flared Kurti', price: 1599, image: 'https://via.placeholder.com/300?text=Georgette+Flared+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Flared georgette kurti for grace.', color: 'Yellow', material: 'Georgette' },
    { id: 48, name: 'Rayon Kurta with Skirt', price: 2199, image: 'https://via.placeholder.com/300?text=Rayon+Kurta+with+Skirt', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Rayon kurta with skirt set.', color: 'Red', material: 'Rayon' },
    { id: 49, name: 'Cotton Kurti with Jacket', price: 1699, image: 'https://via.placeholder.com/300?text=Cotton+Kurti+with+Jacket', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Cotton kurti with jacket layer.', color: 'Blue', material: 'Cotton' },
    { id: 50, name: 'Velvet Anarkali Kurti', price: 3499, image: 'https://via.placeholder.com/300?text=Velvet+Anarkali+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Rich velvet anarkali kurti.', color: 'Green', material: 'Velvet' },
    { id: 51, name: 'Linen Embroidered Kurti', price: 1799, image: 'https://via.placeholder.com/300?text=Linen+Embroidered+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Linen kurti with subtle embroidery.', color: 'Beige', material: 'Linen' },
    { id: 52, name: 'Silk Kurti with Palazzo', price: 3299, image: 'https://via.placeholder.com/300?text=Silk+Kurti+with+Palazzo', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Silk kurti with palazzo pants.', color: 'Gold', material: 'Silk' },
    { id: 53, name: 'Cotton Kurti with Skirt', price: 1499, image: 'https://via.placeholder.com/300?text=Cotton+Kurti+with+Skirt', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Cotton kurti with skirt combo.', color: 'Pink', material: 'Cotton' },
    { id: 54, name: 'Chiffon Straight Kurti', price: 1399, image: 'https://via.placeholder.com/300?text=Chiffon+Straight+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Light chiffon straight kurti.', color: 'White', material: 'Chiffon' },
    { id: 55, name: 'Printed Georgette Kurti', price: 1199, image: 'https://via.placeholder.com/300?text=Printed+Georgette+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Printed georgette kurti.', color: 'Multicolor', material: 'Georgette' },
    { id: 56, name: 'Rayon Kurti with Dupatta', price: 2099, image: 'https://via.placeholder.com/300?text=Rayon+Kurti+with+Dupatta', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Rayon kurti with dupatta set.', color: 'Purple', material: 'Rayon' },
    { id: 57, name: 'Silk Kurti with Embroidery', price: 2699, image: 'https://via.placeholder.com/300?text=Silk+Kurti+with+Embroidery', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Silk kurti with intricate embroidery.', color: 'Maroon', material: 'Silk' },
    { id: 58, name: 'Cotton Flared Kurti', price: 1299, image: 'https://via.placeholder.com/300?text=Cotton+Flared+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Comfortable flared cotton kurti.', color: 'Blue', material: 'Cotton' },
    { id: 59, name: 'Velvet Straight Kurti', price: 2899, image: 'https://via.placeholder.com/300?text=Velvet+Straight+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Velvet straight kurti for elegance.', color: 'Green', material: 'Velvet' },
    { id: 60, name: 'Linen Printed Kurti', price: 1599, image: 'https://via.placeholder.com/300?text=Linen+Printed+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Printed linen kurti for casual wear.', color: 'Beige', material: 'Linen' },
    
    // Western Wear (IDs 61-90)
    { id: 61, name: 'Denim Kurti Top', price: 1499, image: 'https://via.placeholder.com/300?text=Denim+Kurti+Top', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Stylish denim kurti top.', color: 'Blue', material: 'Denim' },
    { id: 62, name: 'Cotton Tunic Kurti', price: 899, image: 'https://via.placeholder.com/300?text=Cotton+Tunic+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Casual cotton tunic-style kurti.', color: 'White', material: 'Cotton' },
    { id: 63, name: 'Cape Style Kurti', price: 1799, image: 'https://via.placeholder.com/300?text=Cape+Style+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Modern cape-style kurti.', color: 'Black', material: 'Georgette' },
    { id: 64, name: 'Printed Shirt Kurti', price: 1199, image: 'https://via.placeholder.com/300?text=Printed+Shirt+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Shirt-style kurti with prints.', color: 'Multicolor', material: 'Cotton' },
    { id: 65, name: 'Chiffon Overlay Kurti', price: 1599, image: 'https://via.placeholder.com/300?text=Chiffon+Overlay+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Chiffon overlay kurti for a chic look.', color: 'Pink', material: 'Chiffon' },
    { id: 66, name: 'Velvet Crop Kurti', price: 1999, image: 'https://via.placeholder.com/300?text=Velvet+Crop+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Trendy velvet crop kurti.', color: 'Maroon', material: 'Velvet' },
    { id: 67, name: 'Linen Shirt Kurti', price: 1299, image: 'https://via.placeholder.com/300?text=Linen+Shirt+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Linen shirt-style kurti.', color: 'Beige', material: 'Linen' },
    { id: 68, name: 'Silk High-Low Kurti', price: 2299, image: 'https://via.placeholder.com/300?text=Silk+High-Low+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Silk high-low kurti for a modern twist.', color: 'Gold', material: 'Silk' },
    { id: 69, name: 'Cotton Peplum Kurti', price: 999, image: 'https://via.placeholder.com/300?text=Cotton+Peplum+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Peplum-style cotton kurti.', color: 'Red', material: 'Cotton' },
    { id: 70, name: 'Georgette Wrap Kurti', price: 1699, image: 'https://via.placeholder.com/300?text=Georgette+Wrap+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Wrap-style georgette kurti.', color: 'Blue', material: 'Georgette' },
    { id: 71, name: 'Rayon Off-Shoulder Kurti', price: 1899, image: 'https://via.placeholder.com/300?text=Rayon+Off-Shoulder+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Off-shoulder rayon kurti.', color: 'Pink', material: 'Rayon' },
    { id: 72, name: 'Silk Cold-Shoulder Kurti', price: 2099, image: 'https://via.placeholder.com/300?text=Silk+Cold-Shoulder+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Cold-shoulder silk kurti.', color: 'Black', material: 'Silk' },
    { id: 73, name: 'Cotton Maxi Kurti', price: 1399, image: 'https://via.placeholder.com/300?text=Cotton+Maxi+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Maxi-style cotton kurti.', color: 'Green', material: 'Cotton' },
    { id: 74, name: 'Chanderi Shirt Kurti', price: 1799, image: 'https://via.placeholder.com/300?text=Chanderi+Shirt+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Chanderi shirt-style kurti.', color: 'Peach', material: 'Chanderi Silk' },
    { id: 75, name: 'Printed Asymmetrical Kurti', price: 1099, image: 'https://via.placeholder.com/300?text=Printed+Asymmetrical+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Asymmetrical kurti with prints.', color: 'Multicolor', material: 'Rayon' },
    { id: 76, name: 'Silk Belted Kurti', price: 1999, image: 'https://via.placeholder.com/300?text=Silk+Belted+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Belted silk kurti for a fitted look.', color: 'Purple', material: 'Silk' },
    { id: 77, name: 'Georgette Ruffle Kurti', price: 1499, image: 'https://via.placeholder.com/300?text=Georgette+Ruffle+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Ruffle-detail georgette kurti.', color: 'Yellow', material: 'Georgette' },
    { id: 78, name: 'Rayon Flared Top Kurti', price: 1699, image: 'https://via.placeholder.com/300?text=Rayon+Flared+Top+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Flared rayon top kurti.', color: 'Red', material: 'Rayon' },
    { id: 79, name: 'Cotton Crop Top Kurti', price: 1299, image: 'https://via.placeholder.com/300?text=Cotton+Crop+Top+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Cotton crop top kurti.', color: 'White', material: 'Cotton' },
    { id: 80, name: 'Velvet Jacket Kurti', price: 2399, image: 'https://via.placeholder.com/300?text=Velvet+Jacket+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Velvet jacket-style kurti.', color: 'Maroon', material: 'Velvet' },
    { id: 81, name: 'Linen High-Low Kurti', price: 1599, image: 'https://via.placeholder.com/300?text=Linen+High-Low+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'High-low linen kurti.', color: 'Beige', material: 'Linen' },
    { id: 82, name: 'Silk Peplum Top Kurti', price: 2199, image: 'https://via.placeholder.com/300?text=Silk+Peplum+Top+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Silk peplum top kurti.', color: 'Gold', material: 'Silk' },
    { id: 83, name: 'Cotton Shirt Style Kurti', price: 1199, image: 'https://via.placeholder.com/300?text=Cotton+Shirt+Style+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Shirt-style cotton kurti.', color: 'Blue', material: 'Cotton' },
    { id: 84, name: 'Chiffon Tiered Kurti', price: 1799, image: 'https://via.placeholder.com/300?text=Chiffon+Tiered+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Tiered chiffon kurti.', color: 'Pink', material: 'Chiffon' },
    { id: 85, name: 'Printed Denim Kurti', price: 1399, image: 'https://via.placeholder.com/300?text=Printed+Denim+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Printed denim kurti.', color: 'Blue', material: 'Denim' },
    { id: 86, name: 'Rayon Tunic Top Kurti', price: 1599, image: 'https://via.placeholder.com/300?text=Rayon+Tunic+Top+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Tunic-style rayon kurti.', color: 'Green', material: 'Rayon' },
    { id: 87, name: 'Silk Overlay Kurti', price: 1999, image: 'https://via.placeholder.com/300?text=Silk+Overlay+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Silk overlay kurti.', color: 'Purple', material: 'Silk' },
    { id: 88, name: 'Cotton Flared Western Kurti', price: 1299, image: 'https://via.placeholder.com/300?text=Cotton+Flared+Western+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Flared western-style cotton kurti.', color: 'White', material: 'Cotton' },
    { id: 89, name: 'Velvet High-Low Kurti', price: 2499, image: 'https://via.placeholder.com/300?text=Velvet+High-Low+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'High-low velvet kurti.', color: 'Maroon', material: 'Velvet' },
    { id: 90, name: 'Linen Cape Kurti', price: 1699, image: 'https://via.placeholder.com/300?text=Linen+Cape+Kurti', sideView: 'https://via.placeholder.com/300?text=Side+View', leftView: 'https://via.placeholder.com/300?text=Left+View', rightView: 'https://via.placeholder.com/300?text=Right+View', description: 'Cape-style linen kurti.', color: 'Beige', material: 'Linen' },
  ];

  const product = products.find(p => p.id === parseInt(id)) || products[0];

  const handleShare = () => {
    const shareUrl = `${window.location.origin}/product/${product.id}`;
    const whatsappUrl = `https://wa.me/?text=Check%20out%20this%20${product.name}%20at%20Kurti%20Store:%20${encodeURIComponent(shareUrl)}`;
    window.open(whatsappUrl, '_blank');
  };

  return (
    <div className="container mx-auto px-4 py-12">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div>
          <img src={product.image} alt={product.name} className="w-full h-96 object-cover rounded-lg mb-4" />
          <div className="grid grid-cols-3 gap-4">
            <img src={product.sideView} alt="Side View" className="w-full h-32 object-cover rounded-lg" />
            <img src={product.leftView} alt="Left View" className="w-full h-32 object-cover rounded-lg" />
            <img src={product.rightView} alt="Right View" className="w-full h-32 object-cover rounded-lg" />
          </div>
        </div>
        <div>
          <h1 className="text-3xl font-bold mb-4">{product.name}</h1>
          <p className="text-gray-600 mb-4">₹{product.price}</p>
          <div className="mb-4">
            <h3 className="text-lg font-semibold mb-2">Size</h3>
            <div className="flex space-x-2">
              {['M', 'L', 'XL', '2XL'].map(size => (
                <button
                  key={size}
                  onClick={() => setSelectedSize(size)}
                  className={`border rounded-full px-4 py-2 ${
                    selectedSize === size ? 'bg-pink-600 text-white' : 'bg-gray-200 text-gray-700'
                  } hover:bg-pink-500 hover:text-white transition-colors`}
                >
                  {size}
                </button>
              ))}
            </div>
          </div>
          <div className="mb-4">
            <h3 className="text-lg font-semibold mb-2">Quantity</h3>
            <div className="flex items-center space-x-2">
              <button
                onClick={() => setQuantity(Math.max(1, quantity - 1))}
                className="bg-gray-200 px-3 py-1 rounded-l-full hover:bg-gray-300"
              >
                -
              </button>
              <span className="px-4 py-1 border-t border-b">{quantity}</span>
              <button
                onClick={() => setQuantity(quantity + 1)}
                className="bg-gray-200 px-3 py-1 rounded-r-full hover:bg-gray-300"
              >
                +
              </button>
            </div>
          </div>
          <button
            onClick={handleShare}
            className="bg-green-500 text-white px-6 py-2 rounded-full hover:bg-green-600 transition-colors flex items-center mb-6"
          >
            <svg className="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 24 24">
              <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.074-.297-.15-1.255-.463-2.39-1.475-.883-.812-1.48-1.77-1.48-2.91 0-.634.233-1.218.652-1.697.42-.477.956-.766 1.535-.788.58-.022 1.13.198 1.63.57.501.373 1.883 1.25 1.883 2.975 0 1.726-1.883 3.447-1.62 3.595.263.148 1.547-.074 2.39-.694.846-.62 1.49-1.39 1.667-1.64.177-.248.099-.471-.074-.644zM12 0C5.373 0 0 5.373 0 12c0 2.137.561 4.248 1.62 6.095L0 24l5.904-1.62A11.934 11.934 0 0012 24c6.627 0 12-5.373 12-12S18.627 0 12 0zm0 22.182c-1.978 0-3.84-.561-5.447-1.535L5.03 21.18l.533-1.523A10.073 10.073 0 013.818 12 10.182 10.182 0 0112 1.818c5.635 0 10.182 4.547 10.182 10.182S17.635 22.182 12 22.182z"/>
            </svg>
            Share on WhatsApp
          </button>
          <div className="border-t pt-6">
            <h3 className="text-lg font-semibold mb-2">Product Description</h3>
            <p className="text-gray-600 mb-2">{product.description}</p>
            <p className="text-gray-600"><span className="font-semibold">Color:</span> {product.color}</p>
            <p className="text-gray-600"><span className="font-semibold">Material:</span> {product.material}</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ProductDetails;